path:
  input: /in/
  output: /out/
  ffmpeg: ffmpeg

audio:
  output_format: mp3
  bitrate: 320
  bitrate_type: cbr
  sample_rate: 44100
  extensions_to_convert: flac, wav

advance:
  thread_count: max
  match_method: date_size
  extensions_to_ignore: 7z, zip, ini, itc2, itl, itdb, m3u, jpg, jpeg, log, pdf, png, cue, sfk
  enable_custom_command: false
  custom_command: ffmpeg -i [INPUT] -acodec alac [OUTPUT]